# Pandas

In [144]:
import pandas as pd

A DataFrame is pandas’ table of rows and columns, like a spreadsheet.

In [145]:
# Create a dataframe
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["A","B","c"])
df

   A  B  c
0  1  2  3
1  4  5  6
2  7  8  9

In [146]:
# Get first and last rows of the dataframe
print(f"First two rows: \n{df.head(2)} ")
print(f"Last two rows: \n{df.tail(2)} ")

# Get the column name
print(f"\nColumn: {df.columns} ")

First two rows:
   A  B  c
0  1  2  3
1  4  5  6
Last two rows:
   A  B  c
1  4  5  6
2  7  8  9

Column: Index(['A', 'B', 'c'], dtype='str')

In [147]:
# converts the DataFrame’s index labels into a Python list.
print(f"Dataframe index: {df.index} ")
print(f"Convert index into list : {df.index.tolist()} ")

# Specifiy the index when creating dataframe
df=pd.DataFrame([[1,2,3],[1,5,6]],columns=["A","B","C"],index=["x","y"])
print(df)

# Information about dataframe
df.info()

# Use describe to know more information about dta
print(df.describe())

# Find unique values
print(f"Unique value in the column A : {df["A"].unique()} ")

# Find shape of the dataframe
print(f"Shape: {df.shape} ")

# Totol number of items
print(f"Number of items in dataframe: {df.size} ")

Dataframe index: RangeIndex(start=0, stop=3, step=1)
Convert index into list : [0, 1, 2]
   A  B  C
x  1  2  3
y  1  5  6
<class 'pandas.DataFrame'>
Index: 2 entries, x to y
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      int64
 1   B       2 non-null      int64
 2   C       2 non-null      int64
dtypes: int64(3)
memory usage: 66.0 bytes
         A        B        C
count  2.0  2.00000  2.00000
mean   1.0  3.50000  4.50000
std    0.0  2.12132  2.12132
min    1.0  2.00000  3.00000
25%    1.0  2.75000  3.75000
50%    1.0  3.50000  4.50000
75%    1.0  4.25000  5.25000
max    1.0  5.00000  6.00000
Unique value in the column A : [1]
Shape: (2, 3)
Number of items in dataframe: 6

# Loading in Dataframe from files

In [148]:
# Read coffee csv file
coffee=pd.read_csv("coffee.csv")
print(f"Top 3 rows of coffee folder:\n{coffee.head(3)} ")

Top 3 rows of coffee folder:
       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

# Accessing Data with Pandas

- .loc selects by row label.
- .iloc selects by row position (starting at 0)

In [149]:
# get full dataframe
print(f"Dataset:\n{coffee} ")
print(f"\n Get random sample :\n{coffee.sample(3,random_state=42)} ")

# update values in dataframe
coffee.loc[3:,'Units Sold']=100
print(f"Updated Dataframe:\n{coffee} ")

# access the row/column
print(f"First row:\n{coffee.loc[0]}\nFirst three rows:\n{coffee.loc[[0,1,2]]} ")

# Loc uses label
print(f"Get Day and unit sold for fifth to 7the row:\n{coffee.loc[5:8,["Day","Units Sold"]]} ")

# iloc uses position, we are changing index value and then try to access 
coffee.index=coffee.Day
print(f"First 3 rows:\n{coffee.iloc[0:3]} ")
print(f"Get only Monday:\n{coffee.loc["Monday"]} ")

# To access the column 
print(f"Day column:\n{coffee["Day"]}")

# Sort the values
print(f"\n\n\nSorted Unit sold column:\n{coffee.sort_values(["Units Sold","Coffee Type"],ascending=False)} ")

# Iterate over dataframe with for loop
for index,row in coffee.iterrows():
    print(index)
    print(row['Units Sold'],"\n")

Dataset:
          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

 Get random sample :
         Day Coffee Type  Units Sold
9     Friday       Latte          35
11  Saturday       Latte          35
0     Monday    Espresso          25
Updated Dataframe:
          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte         100
4   Wednesday    Espresso         100
5   Wednesday       Latte         100
6    Thursday    Espresso         100
7    Thursday       Latte         100
8      Friday    Espresso         100
9      Friday       Latte         100
10   Saturday    Espresso         100
11   Saturday       Latte         100
12     Sunday    Espresso         100
13     Sunday       Latte         100
First row:
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object
First three rows:
       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30
Get Day and unit sold for fifth to 7the row:
         Day  Units Sold
5  Wednesday         100
6   Thursday         100
7   Thursday         100
8     Friday         100
First 3 rows:
             Day Coffee Type  Units Sold
Day
Monday    Monday    Espresso          25
Monday    Monday       Latte          15
Tuesday  Tuesday    Espresso          30
Get only Monday:
           Day Coffee Type  Units Sold
Day
Monday  Monday    Espresso          25
Monday  Monday       Latte          15
Day column:
Day
Monday          Monday
Monday          Monday
Tuesday        Tuesday
Tuesday        Tuesday
Wednesday    Wednesday
Wednesday    Wednesday
Thursday      Thursday
Thursday      Thursday
Friday          Friday
Friday          Friday
Saturday      Saturday
Saturday      Saturday
Sunday          Sunday
Sunday          Sunday
Name: Day, dtype: str



Sorted Unit sold column:
                 Day Coffee Type  Units Sold
Day
Tuesday      Tuesday       Latte         100
Wednesday  Wednesday       Latte         100
Thursday    Thursday       Latte         100
Friday        Friday       Latte         100
Saturday    Saturday       Latte         100
Sunday        Sunday       Latte         100
Wednesday  Wednesday    Espresso         100
Thursday    Thursday    Espresso         100
Friday        Friday    Espresso         100
Saturday    Saturday    Espresso         100
Sunday        Sunday    Espresso         100
Tuesday      Tuesday    Espresso          30
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Monday
25

Monday
15

Tuesday
30

Tuesday
100

Wednesday
100

Wednesday
100

Thursday
100

Thursday
100

Friday
100

Friday
100

Saturday
100

Saturday
100

Sunday
100

Sunday
100

# Filterning Data

In [150]:
# Read bios file
bios=pd.read_csv('bios.csv')

# Filter height greater than 215
print(f"\nHeight Greater than 215\n{bios.loc[bios['height_cm']>215,['name']]} ")

# Another way
print(bios[bios['height_cm']>215][['name','height_cm']])

# height greater than 215 and born country is usa
bios[(bios['height_cm']>215) & (bios['born_country']=='USA')]

# name contains keith and patrick
bios[bios['name'].str.contains('Keith|patrick',case=False)]

# Filter name start with keith and country as usa france and great britain
bios[(bios['born_country'].isin(['USA','GBR','FRA'])) & (bios['name'].str.startswith("Keith"))
]

# Get country as usa and city as seattle
bios.query('born_country=="USA" and born_city=="Seattle"')

Height Greater than 215
                         name
5089       Viktor Pankrashkin
5583     Paulinho Villas Boas
5673           Gunther Behnke
5716                 Uwe Blab
5781           Tommy Burleson
5796            Andy Campbell
6223              Lars Hansen
6270              Hu Zhangbao
6409         Sergey Kovalenko
6420            Jānis Krūmiņš
6504              Luc Longley
6722         Shaquille O'Neal
6937           David Robinson
6978          Arvydas Sabonis
7074           Paulo da Silva
7188       Vladimir Tkachenko
7281         Stojko Vranković
7376      Eurelijus Žukauskas
52608         Aleksey Kazakov
82100           Frédéric Weis
89070                Yao Ming
89075          Roberto Dueñas
107408       Peter John Ramos
112312           Stanko Barać
112332    Andreas Glyniadakis
112337          Hamed Haddadi
118663         Timofey Mozgov
118676        Dmitry Musersky
120266           Zhang Zhaoxu
121694            Salah Mejri
123850         Tyson Chandler
130460               Li Muhao
130461                Zhou Qi
138671          Ondřej Balvín
139365         Moustapha Fall
                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

# Adding and removing column

In [ ]:
# Create a copy of the dataframe
coffee_new=coffee.copy()
coffee_new

# add new column price
coffee_new['price']=4.99
print(f"created new column:\n{coffee_new} ")

# Modify the price as per coffee type
import numpy as np
coffee_new['new price']=np.where(coffee_new['Coffee Type']=='Espresso',3.99,5.99)
print(f"Updated new price:\n{coffee_new} ")

# Drop the row 
coffee.drop('Monday')

# Drop the column
print(f"Dropped the column price:\n{coffee_new.drop(columns=['price'])} ")

# Add inplace to make update
coffee_new.drop(columns=['price'],inplace=True)

# just take only column that we need instead of using drop 
coffee_new=coffee_new[['Day','Units Sold','new price']]

# create new column by computation
coffee_new['Revenue']=coffee_new['Units Sold']*coffee_new['new price']

# create new column by computation
coffee_new['Revenue']=coffee_new['Units Sold']*coffee_new['new price']
coffee_new.head(3)

# Rename the column
coffee_new.rename(columns={'new price':'price'},inplace=True)

created new column:
                 Day Coffee Type  Units Sold  price
Day
Monday        Monday    Espresso          25   4.99
Monday        Monday       Latte          15   4.99
Tuesday      Tuesday    Espresso          30   4.99
Tuesday      Tuesday       Latte         100   4.99
Wednesday  Wednesday    Espresso         100   4.99
Wednesday  Wednesday       Latte         100   4.99
Thursday    Thursday    Espresso         100   4.99
Thursday    Thursday       Latte         100   4.99
Friday        Friday    Espresso         100   4.99
Friday        Friday       Latte         100   4.99
Saturday    Saturday    Espresso         100   4.99
Saturday    Saturday       Latte         100   4.99
Sunday        Sunday    Espresso         100   4.99
Sunday        Sunday       Latte         100   4.99
Updated new price:
                 Day Coffee Type  Units Sold  price  new price
Day
Monday        Monday    Espresso          25   4.99       3.99
Monday        Monday       Latte          15   4.99       5.99
Tuesday      Tuesday    Espresso          30   4.99       3.99
Tuesday      Tuesday       Latte         100   4.99       5.99
Wednesday  Wednesday    Espresso         100   4.99       3.99
Wednesday  Wednesday       Latte         100   4.99       5.99
Thursday    Thursday    Espresso         100   4.99       3.99
Thursday    Thursday       Latte         100   4.99       5.99
Friday        Friday    Espresso         100   4.99       3.99
Friday        Friday       Latte         100   4.99       5.99
Saturday    Saturday    Espresso         100   4.99       3.99
Saturday    Saturday       Latte         100   4.99       5.99
Sunday        Sunday    Espresso         100   4.99       3.99
Sunday        Sunday       Latte         100   4.99       5.99
Dropped the column price:
                 Day Coffee Type  Units Sold  new price
Day
Monday        Monday    Espresso          25       3.99
Monday        Monday       Latte          15       5.99
Tuesday      Tuesday    Espresso          30       3.99
Tuesday      Tuesday       Latte         100       5.99
Wednesday  Wednesday    Espresso         100       3.99
Wednesday  Wednesday       Latte         100       5.99
Thursday    Thursday    Espresso         100       3.99
Thursday    Thursday       Latte         100       5.99
Friday        Friday    Espresso         100       3.99
Friday        Friday       Latte         100       5.99
Saturday    Saturday    Espresso         100       3.99
Saturday    Saturday       Latte         100       5.99
Sunday        Sunday    Espresso         100       3.99
Sunday        Sunday       Latte         100       5.99

In [ ]:
# split the name into first name and find only for keith first name
bios_new=bios.copy()
bios_new['first_name']=bios_new['name'].str.split(' ').str[0]
print(bios_new.query('first_name=="Keith"'))

        athlete_id               name   born_date     born_city  \
1897          1907       Keith Hanlon  1966-09-01           NaN
3505          3517      Keith Wallace  1961-03-29       Preston
6228          6255      Keith Hartley  1940-10-15     Vancouver
8898          8946        Keith Mwila  1966-01-01           NaN
12053        12118       Keith Hervey  1898-11-03        Fulham
...            ...                ...         ...           ...
99921       100722       Keith Carney  1970-02-03    Providence
102227      103168      Keith Beavers  1983-02-09        London
109900      111105  Keith Cumberpatch  1927-08-25  Christchurch
115973      117348    Keith Sanderson  1975-02-02      Plymouth
122121      124176     Keith Ferguson  1979-09-07          Sale

             born_region born_country            NOC  height_cm  weight_kg  \
1897                 NaN          NaN        Ireland        NaN        NaN
3505             England          GBR  Great Britain      165.0       51.0
6228    British Columbia          CAN         Canada      200.0       85.0
8898                 NaN          NaN         Zambia        NaN        NaN
12053            England          GBR  Great Britain        NaN        NaN
...                  ...          ...            ...        ...        ...
99921       Rhode Island          USA  United States      188.0       93.0
102227           Ontario          CAN         Canada      185.0       75.0
109900        Canterbury          NZL    New Zealand        NaN        NaN
115973     Massachusetts          USA  United States      183.0       95.0
122121          Victoria          AUS      Australia      176.0       78.0

         died_date first_name
1897           NaN      Keith
3505    1999-12-31      Keith
6228           NaN      Keith
8898    1993-01-09      Keith
12053   1973-02-22      Keith
...            ...        ...
99921          NaN      Keith
102227         NaN      Keith
109900  2013-11-15      Keith
115973         NaN      Keith
122121         NaN      Keith

[64 rows x 11 columns]

In [176]:
# Date time
bios_new['born_date_time']=pd.to_datetime(bios_new['born_date'],format="%Y-%m-%d")
bios_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   athlete_id      145500 non-null  int64
 1   name            145500 non-null  str
 2   born_date       143693 non-null  str
 3   born_city       110908 non-null  str
 4   born_region     110908 non-null  str
 5   born_country    110908 non-null  str
 6   NOC             145499 non-null  str
 7   height_cm       106651 non-null  float64
 8   weight_kg       102070 non-null  float64
 9   died_date       33940 non-null   str
 10  first_name      145500 non-null  object
 11  born_date_time  143693 non-null  datetime64[us]
 12  Born_year       143693 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(1), object(1), str(7)
memory usage: 21.9+ MB

In [177]:
bios_new['Born_year']=bios_new['born_date_time'].dt.year
bios_new[['name','Born_year']]

                         name  Born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [181]:
bios_new['Height_Category']=bios_new['height_cm'].apply(lambda x: "Short" if x<165 else('Average' if x<185 else 'Tall'))
bios_new.head(3)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_date_time,Born_year,height_category,Height_Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average,Average

In [183]:
def categorize_athlete(row):
    if row['height_cm']<175 and row['weight_kg']<70:
        return 'LightWeight'
    elif row['height_cm']<185 or row['weight_kg']<=80:
        return 'MiddleWeight'
    else:
        return 'HeavyWeight'
bios_new["category"]=bios_new.apply(categorize_athlete,axis=1)
bios_new.head(2)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_date_time,Born_year,height_category,Height_Category,category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall,Tall,HeavyWeight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average,Average,MiddleWeight

# Save the dataframe as csv

In [178]:
bios_new.to_csv('bios_new.csv',index=False)

# Merging and concatenating Data

In [197]:
nocs=pd.read_csv('noc_regions.csv')
bios=pd.read_csv('bios.csv')
bios_new=pd.merge(bios,nocs,left_on='born_country',right_on='NOC',how='left')
bios_new.rename(columns={'region':'born_country_full'},inplace=True)

In [201]:
bios_new[bios_new['NOC_x'] != bios_new['born_country_full']][['name','NOC_x','born_country_full']]

                       name    NOC_x born_country_full
4              Albert Canet   France                UK
12                J. Defert   France               NaN
13           Étienne Durand   France               NaN
16               Guy Forget   France           Morocco
27       Guy, Baron Lejeune   France               NaN
...                     ...      ...               ...
145491        Matthew Wepke  Jamaica               NaN
145493   Landysh Falyakhova      ROC            Russia
145495    Polina Luchnikova      ROC            Russia
145496  Valeriya Merkusheva      ROC            Russia
145497      Yuliya Smirnova      ROC            Russia

[73210 rows x 3 columns]

In [ ]:
# Concat two dataframe
usa=bios[bios['born_country']=='USA'].copy()
gbr=bios[bios['born_country']=='GBR'].copy()
new_df=pd.concat([usa,gbr])
new_df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN

In [213]:
results = pd.read_parquet('results.parquet')
combined_df=pd.merge(results,bios,on='athlete_id',how='left')
combined_df

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN,Marián Skupek,2001-07-12,Gelnica,Košice,SVK,Slovakia,196.0,108.0,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN,Elsa Fermbäck,1998-03-28,Vemdalen,Jämtland,SWE,Sweden,NaN,NaN,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN,Hilma Lövblom,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN,Hilma Lövblom,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN,Charlotta Säfvenberg,1994-10-07,Kungsbacka,Halland,SWE,Sweden,NaN,NaN,NaN

# Handling Null values

In [ ]:
coffee=pd.read_csv('coffee.csv')
coffee.loc[[0,1],'Units Sold']=15
coffee.loc[[2,3],'Units Sold']=np.nan



# ways to fill NAN
coffee=coffee.fillna(1000)
coffee.fillna(coffee['Units Sold'].mean())

coffee=pd.read_csv('coffee.csv')
coffee.loc[[0,1],'Units Sold']=15
coffee.loc[[2,3],'Units Sold']=np.nan
coffee['Units Sold']=coffee['Units Sold'].interpolate()
coffee

# Drop rows with nan
coffee.loc[[0,1],'Units Sold']=15
coffee.loc[[2,3],'Units Sold']=np.nan
coffee.dropna(subset=['Units Sold'],inplace=True)

# Get rows that has NAN and does not has NAN
coffee=pd.read_csv('coffee.csv')
coffee.loc[[0,1],'Units Sold']=15
coffee.loc[[2,3],'Units Sold']=np.nan
coffee[coffee['Units Sold'].isna()]
coffee[coffee['Units Sold'].notna()]

          Day Coffee Type  Units Sold
0      Monday    Espresso        15.0
1      Monday       Latte        15.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

# Aggregating Data

In [245]:
bios['born_city'].value_counts()
bios[bios['born_country']=='USA']['born_region'].value_counts().tail()

born_region
South Dakota     27
West Virginia    24
Delaware         22
North Dakota     16
Wyoming          14
Name: count, dtype: int64

In [250]:
coffee.groupby(['Coffee Type'])['Units Sold'].sum()
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    37.500000
Latte       29.166667
Name: Units Sold, dtype: float64

In [253]:
coffee_new=coffee.copy()
coffee_new

# add new column price
coffee_new['price']=4.99

# Modify the price as per coffee type
import numpy as np
coffee_new['new price']=np.where(coffee_new['Coffee Type']=='Espresso',3.99,5.99)

coffee_new.groupby(['Coffee Type']).agg({'Units Sold':'sum','price':'mean'})

             Units Sold  price
Coffee Type
Espresso          225.0   4.99
Latte             175.0   4.99