# Reading files

In [1]:
import pandas as pd

In [2]:
# read the csv file
data_frame=pd.read_csv('countries of the world.csv')
data_frame

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [3]:
# read text file
data_frame=pd.read_table('countries of the world.txt')
data_frame

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [4]:
# read json file
data_frame=pd.read_json('json_sample.json')
data_frame

,12 Strong,A Fantastic Woman (Una Mujer Fantástica),All The Money In The World,Bilal: A New Breed Of Hero,Call Me By Your Name,Darkest Hour,Den Of Thieves,Ferdinand,Fifty Shades Freed,Film Stars Don'T Die In Liverpool,...,The 15:17 To Paris,The Commuter,The Disaster Artist,The Greatest Showman,The Insult (L'Insulte),The Post,The Shape Of Water,"Three Billboards Outside Ebbing, Missouri",Till The End Of The World,Winchester
0,"{'Genre': 'Action', 'Gross': '$453,173', 'IMDB...","{'popcornscore': 83, 'rating': 'R', 'tomatosco...","{'popcornscore': 71, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG13', 'tomato...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': 84, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$491,898', 'IMDB...","{'popcornscore': 49, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 69, 'rating': 'R', 'tomatosco...",...,"{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$627,248', 'I...","{'popcornscore': 86, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$463,228', 'I...","{'Genre': 'Adventure', 'Gross': '$448,287', 'I...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': -1, 'rating': 'NR', 'tomatosc...","{'Genre': 'Biography', 'Gross': '$696,786', 'I..."

In [5]:
# read excel 
data_frame1=pd.read_excel('world_population_excel_workbook.xlsx')
data_frame1

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El AaiÃºn,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [6]:
# read second sheet from excel 
data_frame=pd.read_excel('world_population_excel_workbook.xlsx',sheet_name='Sheet1')
data_frame

     Rank CCA3            Country           Capital
0      36  AFG        Afghanistan             Kabul
1     138  ALB            Albania            Tirana
2      34  DZA            Algeria           Algiers
3     213  ASM     American Samoa         Pago Pago
4     203  AND            Andorra  Andorra la Vella
..    ...  ...                ...               ...
229   226  WLF  Wallis and Futuna          Mata-Utu
230   172  ESH     Western Sahara         El AaiÃºn
231    46  YEM              Yemen             Sanaa
232    63  ZMB             Zambia            Lusaka
233    74  ZWE           Zimbabwe            Harare

[234 rows x 4 columns]

In [7]:
# Set option to view all the rows of the file
pd.set_option('display.max.rows',235)
pd.set_option('display.max.column',40)

In [8]:
# Get information of the file
data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     234 non-null    int64
 1   CCA3     234 non-null    str
 2   Country  234 non-null    str
 3   Capital  234 non-null    str
dtypes: int64(1), str(3)
memory usage: 7.4 KB

In [9]:
# Get shape of the dataframe
print(f"Shape of the dataframe : {data_frame.shape} ")

# Get top 10 rows
print(f"Top 10 rows:\n{data_frame.head(10)} ")

# Get last 10 rows
print(f"\n\nLast 10 rows:\n{data_frame.tail(10)} ")

# Get specific column
print(f"Rank column:\n{data_frame['Rank']} ")

# Get specific row using index
print(f"\n\nSpecific row:\n{data_frame.loc[224]} ")

# Get specific row using position
print(f"\n\n\n Specific row:\n{data_frame.iloc[1]}")

Shape of the dataframe : (234, 4)
Top 10 rows:
   Rank CCA3              Country           Capital
0    36  AFG          Afghanistan             Kabul
1   138  ALB              Albania            Tirana
2    34  DZA              Algeria           Algiers
3   213  ASM       American Samoa         Pago Pago
4   203  AND              Andorra  Andorra la Vella
5    42  AGO               Angola            Luanda
6   224  AIA             Anguilla        The Valley
7   201  ATG  Antigua and Barbuda    Saint Johnâ€™s
8    33  ARG            Argentina      Buenos Aires
9   140  ARM              Armenia           Yerevan


Last 10 rows:
     Rank CCA3            Country       Capital
224    43  UZB         Uzbekistan      Tashkent
225   181  VUT            Vanuatu     Port-Vila
226   234  VAT       Vatican City  Vatican City
227    51  VEN          Venezuela       Caracas
228    16  VNM            Vietnam         Hanoi
229   226  WLF  Wallis and Futuna      Mata-Utu
230   172  ESH     Western Sahara     El AaiÃºn
231    46  YEM              Yemen         Sanaa
232    63  ZMB             Zambia        Lusaka
233    74  ZWE           Zimbabwe        Harare
Rank column:
0       36
1      138
2       34
3      213
4      203
5       42
6      224
7      201
8       33
9      140
10     198
11      55
12      99
13      91
14     176
15     154
16       8
17     186
18      96
19      81
20     177
21      77
22     206
23     165
24      80
25     137
26     144
27       7
28     221
29     175
30     108
31      58
32      78
33      73
34      53
35      39
36     171
37     205
38     117
39      69
40      65
41       1
42      28
43     163
44     223
45     124
46     130
47      85
48     189
49     158
50      88
51     115
52     160
53     204
54      84
55      15
56      67
57      14
58     112
59     152
60     132
61     156
62     159
63      12
64     231
65     209
66     162
67     118
68      23
69     184
70     183
71     146
72     142
73     131
74      19
75      47
76     219
77      90
78     208
79     193
80     178
81     191
82      68
83     207
84      75
85     149
86     164
87      82
88      89
89     104
90      94
91     179
92       2
93       4
94      17
95      35
96     125
97     202
98      98
99      25
100     52
101    139
102     11
103    195
104     83
105     66
106     27
107    192
108    129
109    110
110    103
111    151
112    119
113    147
114    121
115    107
116    216
117    141
118    168
119    167
120     50
121     62
122     45
123    174
124     59
125    173
126    215
127    180
128    126
129    157
130    182
131     10
132    194
133    135
134    217
135    134
136    169
137    230
138     40
139     48
140     26
141    145
142    225
143     49
144     71
145    185
146    123
147    106
148     54
149      6
150    232
151     56
152    150
153    210
154    120
155    127
156      5
157    222
158    122
159    128
160     93
161    109
162     44
163     13
164     37
165     92
166    136
167    143
168    114
169    161
170     64
171      9
172     76
173    228
174    211
175    190
176    220
177    229
178    199
179    188
180    218
181    187
182     41
183     72
184    105
185    196
186    102
187    113
188    214
189    116
190    148
191    166
192     70
193     24
194     29
195     86
196     30
197     61
198     32
199    170
200     87
201    101
202     60
203     57
204     95
205     22
206     20
207    155
208    100
209    233
210    197
211    153
212     79
213     18
214    111
215    212
216    227
217     31
218     38
219     97
220     21
221      3
222    200
223    133
224     43
225    181
226    234
227     51
228     16
229    226
230    172
231     46
232     63
233     74
Name: Rank, dtype: int64


Specific row:
Rank               43
CCA3              UZB
Country    Uzbekistan
Capital      Tashkent
Name: 224, dtype: object



 Specific row:
Rank           138
CCA3           ALB
Country    Albania
Capital     Tirana
Name: 1, dtype: object

# Filterning and ordering

In [10]:
# Read the csv file
dataframe=pd.read_csv('world_population.csv')

# Read top 2 rows
print(f"Top 2 rows\n{data_frame.head(2)} ")

# find rank less than equal to 10
print(f"\n\n\nRows less than equal to 10:\n{ data_frame[data_frame['Rank'] <=10]} ")

# Filter only for two countries
countries=['Brazil','Bangladesh']
print(f"\n\n\nOnly these countires\n{data_frame[data_frame['Country'].isin(countries)]} ")

# Find countries with United in it
print(f"\n\n\nCountries contains United:\n{data_frame[data_frame['Country'].str.contains('United')]} ")

# Set the index as Country not just number
dataframe_new=data_frame1.set_index('Country')
print(f"Top 3 row:\n{dataframe_new.head(2)} ")

# Filter the columns
print(f"\n\n\nOnly two column:\n{dataframe_new.filter(items=['Continent','CCA3'],axis=1)} ")

# Filter row
print(dataframe_new.filter(like='United',axis=0) )
print(dataframe_new.loc['United Kingdom'])
print(dataframe_new.iloc[2])

# Sort by rank ascending
data_frame1[data_frame1['Rank']<10].sort_values(by='Rank')
# Sort by rank Desceding
data_frame1[data_frame1['Rank']<10].sort_values(by='Rank',ascending=False)
# Sort by Contient and Country
data_frame1[data_frame1['Rank']<10].sort_values(by=['Continent','Country'])

Top 2 rows
   Rank CCA3      Country Capital
0    36  AFG  Afghanistan   Kabul
1   138  ALB      Albania  Tirana



Rows less than equal to 10:
     Rank CCA3        Country           Capital
16      8  BGD     Bangladesh             Dhaka
27      7  BRA         Brazil          Brasilia
41      1  CHN          China           Beijing
92      2  IND          India         New Delhi
93      4  IDN      Indonesia           Jakarta
131    10  MEX         Mexico       Mexico City
149     6  NGA        Nigeria             Abuja
156     5  PAK       Pakistan         Islamabad
171     9  RUS         Russia            Moscow
221     3  USA  United States  Washington, D.C.



Only these countires
    Rank CCA3     Country   Capital
16     8  BGD  Bangladesh     Dhaka
27     7  BRA      Brazil  Brasilia



Countries contains United:
     Rank CCA3                       Country           Capital
219    97  ARE          United Arab Emirates         Abu Dhabi
220    21  GBR                United Kingdom            London
221     3  USA                 United States  Washington, D.C.
222   200  VIR  United States Virgin Islands  Charlotte Amalie
Top 3 row:
             Rank CCA3 Capital Continent  2022 Population  2020 Population  \
Country
Afghanistan    36  AFG   Kabul      Asia         41128771         38972230
Albania       138  ALB  Tirana    Europe          2842321          2866849

             2015 Population  2010 Population  2000 Population  \
Country
Afghanistan         33753499         28189672         19542982
Albania              2882481          2913399          3182021

             1990 Population  1980 Population  1970 Population  Area (kmÂ²)  \
Country
Afghanistan         10694796         12486631         10752971       652230
Albania              3295066          2941651          2324731        28748

             Density (per kmÂ²)  Growth Rate  World Population Percentage
Country
Afghanistan             63.0587       1.0257                         0.52
Albania                 98.8702       0.9957                         0.04



Only two column:
                                      Continent CCA3
Country
Afghanistan                                Asia  AFG
Albania                                  Europe  ALB
Algeria                                  Africa  DZA
American Samoa                          Oceania  ASM
Andorra                                  Europe  AND
Angola                                   Africa  AGO
Anguilla                          North America  AIA
Antigua and Barbuda               North America  ATG
Argentina                         South America  ARG
Armenia                                    Asia  ARM
Aruba                             North America  ABW
Australia                               Oceania  AUS
Austria                                  Europe  AUT
Azerbaijan                                 Asia  AZE
Bahamas                           North America  BHS
Bahrain                                    Asia  BHR
Bangladesh                                 Asia  BGD
Barbados                          North America  BRB
Belarus                                  Europe  BLR
Belgium                                  Europe  BEL
Belize                            North America  BLZ
Benin                                    Africa  BEN
Bermuda                           North America  BMU
Bhutan                                     Asia  BTN
Bolivia                           South America  BOL
Bosnia and Herzegovina                   Europe  BIH
Botswana                                 Africa  BWA
Brazil                            South America  BRA
British Virgin Islands            North America  VGB
Brunei                                     Asia  BRN
Bulgaria                                 Europe  BGR
Burkina Faso                             Africa  BFA
Burundi                                  Africa  BDI
Cambodia                                   Asia  KHM
Cameroon                                 Africa  CMR
Canada                            North America  CAN
Cape Verde                               Africa  CPV
Cayman Islands                    North America  CYM
Central African Republic                 Africa  CAF
Chad                                     Africa  TCD
Chile                             South America  CHL
China                                      Asia  CHN
Colombia                          South America  COL
Comoros                                  Africa  COM
Cook Islands                            Oceania  COK
Costa Rica                        North America  CRI
Croatia                                  Europe  HRV
Cuba                              North America  CUB
Curacao                           North America  CUW
Cyprus                                   Europe  CYP
Czech Republic                           Europe  CZE
Denmark                                  Europe  DNK
Djibouti                                 Africa  DJI
Dominica                          North America  DMA
Dominican Republic                North America  DOM
DR Congo                                 Africa  COD
Ecuador                           South America  ECU
Egypt                                    Africa  EGY
El Salvador                       North America  SLV
Equatorial Guinea                        Africa  GNQ
Eritrea                                  Africa  ERI
Estonia                                  Europe  EST
Eswatini                                 Africa  SWZ
Ethiopia                                 Africa  ETH
Falkland Islands                  South America  FLK
Faroe Islands                            Europe  FRO
Fiji                                    Oceania  FJI
Finland                                  Europe  FIN
France                                   Europe  FRA
French Guiana                     South America  GUF
French Polynesia                        Oceania  PYF
Gabon                                    Africa  GAB
Gambia                                   Africa  GMB
Georgia                                    Asia  GEO
Germany                                  Europe  DEU
Ghana                                    Africa  GHA
Gibraltar                                Europe  GIB
Greece                                   Europe  GRC
Greenland                         North America  GRL
Grenada                           North America  GRD
Guadeloupe                        North America  GLP
Guam                                    Oceania  GUM
Guatemala                         North America  GTM
Guernsey                                 Europe  GGY
Guinea                                   Africa  GIN
Guinea-Bissau                            Africa  GNB
Guyana                            South America  GUY
Haiti                             North America  HTI
Honduras                          North America  HND
Hong Kong                                  Asia  HKG
Hungary                                  Europe  HUN
Iceland                                  Europe  ISL
India                                      Asia  IND
Indonesia                                  Asia  IDN
Iran                                       Asia  IRN
Iraq                                       Asia  IRQ
Ireland                                  Europe  IRL
Isle of Man                              Europe  IMN
Israel                                     Asia  ISR
Italy                                    Europe  ITA
Ivory Coast                              Africa  CIV
Jamaica                           North America  JAM
Japan                                      Asia  JPN
Jersey                                   Europe  JEY
Jordan                                     Asia  JOR
Kazakhstan                                 Asia  KAZ
Kenya                                    Africa  KEN
Kiribati                                Oceania  KIR
Kuwait                                     Asia  KWT
Kyrgyzstan                                 Asia  KGZ
Laos                                       Asia  LAO
Latvia                                   Europe  LVA
Lebanon                                    Asia  LBN
Lesotho                                  Africa  LSO
Liberia                                  Africa  LBR
Libya                                    Africa  LBY
Liechtenstein                            Europe  LIE
Lithuania                                Europe  LTU
Luxembourg                               Europe  LUX
Macau                                      Asia  MAC
Madagascar                               Africa  MDG
Malawi                                   Africa  MWI
Malaysia                                   Asia  MYS
Maldives                                   Asia  MDV
Mali                                     Africa  MLI
Malta                                    Europe  MLT
Marshall Islands                        Oceania  MHL
Martinique                        North America  MTQ
Mauritania                               Africa  MRT
Mauritius                                Africa  MUS
Mayotte                                  Africa  MYT
Mexico                            North America  MEX
Micronesia                              Oceania  FSM
Moldova                                  Europe  MDA
Monaco                                   Europe  MCO
Mongolia                                   Asia  MNG
Montenegro                               Europe  MNE
Montserrat                        North America  MSR
Morocco                                  Africa  MAR
Mozambique                               Africa  MOZ
Myanmar                                    Asia  MMR
Namibia                                  Africa  NAM
Nauru                                   Oceania  NRU
Nepal                                      Asia  NPL
Netherlands                              Europe  NLD
New Caledonia                           Oceania  NCL
New Zealand                             Oceania  NZL
Nicaragua                         North America  NIC
Niger                                    Africa  NER
Nigeria                                  Africa  NGA
Niue                                    Oceania  NIU
North Korea                                Asia  PRK
North Macedonia                          Europe  MKD
Northern Mariana Islands                Oceania  NFK
Norway                                   Europe  NOR
Oman                                       Asia  OMN
Pakistan                                   Asia  PAK
Palau                                   Oceania  PLW
Palestine                                  Asia  PSE
Panama                            North America  PAN
Papua New Guinea                        Oceania  PNG
Paraguay                          South America  PRY
Peru                              South America  PER
Philippines                                Asia  PHL
Poland                                   Europe  POL
Portugal                                 Europe  PRT
Puerto Rico                       North America  PRI
Qatar                                      Asia  QAT
Republic of the Congo                    Africa  COG
Reunion                                  Africa  REU
Romania                                  Europe  ROU
Russia                                   Europe  RUS
Rwanda                                   Africa  RWA
Saint Barthelemy                  North America  BLM
Saint Kitts and Nevis             North America  KNA
Saint Lucia                       North America  LCA
Saint Martin                      North America  MAF
Saint Pierre and Miquelon         North America  SPM
Saint Vincent and the Grenadines  North America  VCT
Samoa                                   Oceania  WSM
San Marino                               Europe  SMR
Sao Tome and Principe                    Africa  STP
Saudi Arabia                               Asia  SAU
Senegal                                  Africa  SEN
Serbia                                   Europe  SRB
Seychelles                               Africa  SYC
Sierra Leone                             Africa  SLE
Singapore                                  Asia  SGP
Sint Maarten                      North America  SXM
Slovakia                                 Europe  SVK
Slovenia                                 Europe  SVN
Solomon Islands                         Oceania  SLB
Somalia                                  Africa  SOM
South Africa                             Africa  ZAF
South Korea                                Asia  KOR
South Sudan                              Africa  SSD
Spain                                    Europe  ESP
Sri Lanka                                  Asia  LKA
Sudan                                    Africa  SDN
Suriname                          South America  SUR
Sweden                                   Europe  SWE
Switzerland                              Europe  CHE
Syria                                      Asia  SYR
Taiwan                                     Asia  TWN
Tajikistan                                 Asia  TJK
Tanzania                                 Africa  TZA
Thailand                                   Asia  THA
Timor-Leste                                Asia  TLS
Togo                                     Africa  TGO
Tokelau                                 Oceania  TKL
Tonga                                   Oceania  TON
Trinidad and Tobago               North America  TTO
Tunisia                                  Africa  TUN
Turkey                                     Asia  TUR
Turkmenistan                               Asia  TKM
Turks and Caicos Islands          North America  TCA
Tuvalu                                  Oceania  TUV
Uganda                                   Africa  UGA
Ukraine                                  Europe  UKR
United Arab Emirates                       Asia  ARE
United Kingdom                           Europe  GBR
United States                     North America  USA
United States Virgin Islands      North America  VIR
Uruguay                           South America  URY
Uzbekistan                                 Asia  UZB
Vanuatu                                 Oceania  VUT
Vatican City                             Europe  VAT
Venezuela                         South America  VEN
Vietnam                                    Asia  VNM
Wallis and Futuna                       Oceania  WLF
Western Sahara                           Africa  ESH
Yemen                                      Asia  YEM
Zambia                                   Africa  ZMB
Zimbabwe                                 Africa  ZWE
                              Rank CCA3           Capital      Continent  \
Country
United Arab Emirates            97  ARE         Abu Dhabi           Asia
United Kingdom                  21  GBR            London         Europe
United States                    3  USA  Washington, D.C.  North America
United States Virgin Islands   200  VIR  Charlotte Amalie  North America

                              2022 Population  2020 Population  \
Country
United Arab Emirates                  9441129          9287289
United Kingdom                       67508936         67059474
United States                       338289857        335942003
United States Virgin Islands            99465           100442

                              2015 Population  2010 Population  \
Country
United Arab Emirates                  8916899          8481771
United Kingdom                       65224364         62760039
United States                       324607776        311182845
United States Virgin Islands           102803           106142

                              2000 Population  1990 Population  \
Country
United Arab Emirates                  3275333          1900151
United Kingdom                       58850043         57210442
United States                       282398554        248083732
United States Virgin Islands           108185           100685

                              1980 Population  1970 Population  Area (kmÂ²)  \
Country
United Arab Emirates                  1014048           298084        83600
United Kingdom                       56326328         55650166       242900
United States                       223140018        200328340      9372610
United States Virgin Islands            96640            63446          347

                              Density (per kmÂ²)  Growth Rate  \
Country
United Arab Emirates                    112.9322       1.0081
United Kingdom                          277.9289       1.0034
United States                            36.0935       1.0038
United States Virgin Islands            286.6427       0.9937

                              World Population Percentage
Country
United Arab Emirates                                 0.12
United Kingdom                                       0.85
United States                                        4.24
United States Virgin Islands                         0.00
Rank                                 21
CCA3                                GBR
Capital                          London
Continent                        Europe
2022 Population                67508936
2020 Population                67059474
2015 Population                65224364
2010 Population                62760039
2000 Population                58850043
1990 Population                57210442
1980 Population                56326328
1970 Population                55650166
Area (kmÂ²)                      242900
Density (per kmÂ²)             277.9289
Growth Rate                      1.0034
World Population Percentage        0.85
Name: United Kingdom, dtype: object
Rank                                 34
CCA3                                DZA
Capital                         Algiers
Continent                        Africa
2022 Population                44903225
2020 Population                43451666
2015 Population                39543154
2010 Population                35856344
2000 Population                30774621
1990 Population                25518074
1980 Population                18739378
1970 Population                13795915
Area (kmÂ²)                     2381741
Density (per kmÂ²)              18.8531
Growth Rate                      1.0164
World Population Percentage        0.56
Name: Algeria, dtype: object

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
149,6,NGA,Nigeria,Abuja,Africa,218541212,208327405,183995785,160952853,122851984,95214257,72951439,55569264,923768,236.5759,1.0241,2.74
16,8,BGD,Bangladesh,Dhaka,Asia,171186372,167420951,157830000,148391139,129193327,107147651,83929765,67541860,147570,1160.0350,1.0108,2.15
41,1,CHN,China,Beijing,Asia,1425887337,1424929781,1393715448,1348191368,1264099069,1153704252,982372466,822534450,9706961,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1417173173,1396387127,1322866505,1240613620,1059633675,870452165,696828385,557501301,3287590,431.0675,1.0068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,275501339,271857970,259091970,244016173,214072421,182159874,148177096,115228394,1904569,144.6529,1.0064,3.45
156,5,PAK,Pakistan,Islamabad,Asia,235824862,227196741,210969298,194454498,154369924,115414069,80624057,59290872,881912,267.4018,1.0191,2.96
171,9,RUS,Russia,Moscow,Europe,144713314,145617329,144668389,143242599,146844839,148005704,138257420,130093010,17098242,8.4636,0.9973,1.81
221,3,USA,United States,"Washington, D.C.",North America,338289857,335942003,324607776,311182845,282398554,248083732,223140018,200328340,9372610,36.0935,1.0038,4.24
27,7,BRA,Brazil,Brasilia,South America,215313498,213196304,205188205,196353492,175873720,150706446,122288383,96369875,8515767,25.2841,1.0046,2.70

# Indexing

In [11]:
# Read the file
data_frame=pd.read_csv('world_population.csv')
print(data_frame.head(5))

#

   Rank CCA3         Country           Capital Continent  2022 Population  \
0    36  AFG     Afghanistan             Kabul      Asia       41128771.0
1   138  ALB         Albania            Tirana    Europe        2842321.0
2    34  DZA         Algeria           Algiers    Africa       44903225.0
3   213  ASM  American Samoa         Pago Pago   Oceania          44273.0
4   203  AND         Andorra  Andorra la Vella    Europe          79824.0

   2020 Population  2015 Population  2010 Population  2000 Population  \
0       38972230.0       33753499.0       28189672.0       19542982.0
1        2866849.0        2882481.0        2913399.0        3182021.0
2       43451666.0       39543154.0       35856344.0       30774621.0
3          46189.0          51368.0          54849.0          58230.0
4          77700.0          71746.0          71519.0          66097.0

   1990 Population  1980 Population  1970 Population  Area (km²)  \
0       10694796.0       12486631.0       10752971.0    652230.0
1        3295066.0        2941651.0        2324731.0     28748.0
2       25518074.0       18739378.0       13795915.0   2381741.0
3          47818.0          32886.0          27075.0       199.0
4          53569.0          35611.0          19860.0       468.0

   Density (per km²)  Growth Rate  World Population Percentage
0            63.0587       1.0257                         0.52
1            98.8702       0.9957                         0.04
2            18.8531       1.0164                         0.56
3           222.4774       0.9831                         0.00
4           170.5641       1.0100                         0.00